/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
import { Body } from "../models";
import { Body1 } from "../models";
import { InlineResponse200 } from "../models";
import { InlineResponse2001 } from "../models";
import { InlineResponse400 } from "../models";
/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Let's user to login using Email and Password
     * @summary User Login
     * @param {Body} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userLogin: async (body?: Body, options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/login`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        //@ts-ignore
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      const needsSerialization =
        typeof body !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || "";

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * User registration by entering Organisation, Location, Email and Password
     * @summary Creating User Account
     * @param {Body1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userResigter: async (
      body?: Body1,
      options: any = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/register`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        //@ts-ignore
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      const needsSerialization =
        typeof body !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || "";

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function (configuration?: Configuration) {
  return {
    /**
     * Let's user to login using Email and Password
     * @summary User Login
     * @param {Body} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userLogin(
      body?: Body,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<InlineResponse200>
    > {
      const localVarAxiosArgs = await AuthenticationApiAxiosParamCreator(
        configuration
      ).userLogin(body, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * User registration by entering Organisation, Location, Email and Password
     * @summary Creating User Account
     * @param {Body1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async userResigter(
      body?: Body1,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<InlineResponse2001>
    > {
      const localVarAxiosArgs = await AuthenticationApiAxiosParamCreator(
        configuration
      ).userResigter(body, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     * Let's user to login using Email and Password
     * @summary User Login
     * @param {Body} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userLogin(body?: Body, options?: any): AxiosPromise<InlineResponse200> {
      return AuthenticationApiFp(configuration)
        .userLogin(body, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * User registration by entering Organisation, Location, Email and Password
     * @summary Creating User Account
     * @param {Body1} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    userResigter(
      body?: Body1,
      options?: any
    ): AxiosPromise<InlineResponse2001> {
      return AuthenticationApiFp(configuration)
        .userResigter(body, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
  /**
   * Let's user to login using Email and Password
   * @summary User Login
   * @param {Body} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthenticationApi
   */
  public userLogin(body?: Body, options?: any) {
    return AuthenticationApiFp(this.configuration)
      .userLogin(body, options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   * User registration by entering Organisation, Location, Email and Password
   * @summary Creating User Account
   * @param {Body1} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthenticationApi
   */
  public userResigter(body?: Body1, options?: any) {
    return AuthenticationApiFp(this.configuration)
      .userResigter(body, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
