export const deviceData = [
  "ACEA NovoCyte 1000",
  "ACEA NovoCyte 2000",
  "ACEA NovoCyte 2060",
  "ACEA NovoCyte 3000",
  "ACEA NovoCyte Quanteon",
  "Amnis CellStream 4 Laser",
  "Amnis CellStream 7 Laser",
  "Amnis FlowSight",
  "Amnis ImageStream - 1 camera",
  "Amnis ImageStream - 2 camera",
  "BD Accuri C6",
  "BD Aria Fusion",
  "BD Aria II",
  "BD Aria III",
  "BD Calibur  3 color",
  "BD Calibur 4 color",
  "BD FACSCanto",
  "BD FACSCanto 2",
  "BD FACSJazz",
  "BD FACS Lyric",
  "BD FACS Symphony A5",
  "BD FACSVerse 4color",
  "BD FACSVerse 6color",
  "BD FACSVerse 8color",
  "BD Influx",
  "BD LSR2",
  "BD LSR2 Fortessa X-20 (5 Laser)",
  "BD LSR Fortessa",
  "BD Vantage",
  "Beckman Coulter CytoFLEX LX N3-V5-B3-Y5-R3-I2",
  "Beckman Coulter CytoFLEX LX U3-V5-B3-Y5-R3-I2",
  "Beckman Coulter CytoFLEX S N2-V3-B5-R3",
  "Beckman Coulter CytoFLEX S N2-V4-B2-Y4",
  "Beckman Coulter CytoFLEX S V4-B2-Y4-R3",
  "Beckman Coulter CytoFLEX S V4-B4-R3-I2",
  "Beckman Coulter CytoFLEX V5-B5-R3",
  "Beckman Coulter DxFLEX",
  "Beckman Coulter Navios Ex",
  "Beckman Coulter Navios / Gallios",
  "Bio-Rad S3e 2 laser (B/R) 4 color",
  "Bio-Rad S3e 2 laser (B/Y) 4 color",
  "Bio-Rad S3e 3 laser (B/Y/R) 4 color",
  "Bio-Rad S3e 3 laser (V/B/R) 4 color",
  "Bio-Rad ZE5 3 laser (B/Y/R) 17 color",
  "Bio-Rad ZE5 3 laser (V/B/R) 17 color",
  "Bio-Rad ZE5 4 laser 24 color",
  "Bio-Rad ZE5 5 laser 27 color",
  "Guava easyCyte 12; 12HT",
  "Guava easyCyte 5; 5HT",
  "Guava easyCyte 8; 8HT",
  "Guava easyCyte B/G/R; B/G/RHT",
  "Guava easyCyte B/G/V; B/G/VHT",
  "Guava Muse",
  "iCyte Reflection",
  "ImageStream",
  "ImageStream Blue/Red 6 color",
  "IntelliCyt iQue Screener",
  "IntelliCyt iQue Screener Plus",
  "JSAN 4 laser",
  "JSAN 8color [405-488-561nm]",
  "JSAN Jr  Swift",
  "Miltenyi Biotec MACSQuant Analyzer 10 (8 color)",
  "Miltenyi Biotec MACSQuant Analyzer 16",
  "Miltenyi Biotec MACSQuant Analyzer (7 color)",
  "Miltenyi Biotec MACSQuant Tyto Cell Sorter",
  "Miltenyi Biotec MACSQuant VYB",
  "Miltenyi Biotec MACSQuant X",
  "Stratedigm S1000",
  "Stratedigm SE500",
  "Stratedigm SE520 EXi",
  "Sysmex CyFlow Cube 6 Blue",
  "Sysmex CyFlow Cube 6 Blue Red",
  "Sysmex CyFlow Cube 8 Blue Red",
  "Sysmex CyFlow Cube 8 UV Blue Red",
  "Sysmex CyFlow Cube 8 Violet Blue Red",
  "Sysmex CyFlow ML",
  "Sysmex CyFlow SL",
  "Sysmex CyFlow Space Blue Red",
  "Sysmex CyFlow Space UV Blue Red",
  "ThermoFisher Attune NxT (Blue/Green)",
  "ThermoFisher Attune NxT (Blue/Green/Red)",
  "ThermoFisher Attune NxT (Blue/Green/Red/Violet)",
  "ThermoFisher Attune NxT (Blue/Green/Violet)",
  "ThermoFisher Attune NxT (Blue/Red/Violet 6)",
  "ThermoFisher Attune NxT (Blue/Red/Yellow/Violet 6)",
  "ThermoFisher Attune NxT (Blue/Violet 6)",
  "YETI",
  "ACEA NovoCyte Advanteon R4Y6B7",
  "ACEA NovoCyte Advanteon V6Y4B5",
  "ACEA NovoCyte Advanteon V8B7R4",
  "BD FACSCelesta V-B",
  "BD FACSCelesta V-B-R",
  "BD FACSCelesta V-B-UV",
  "BD FACSCelesta V-B-Y",
  "Sony FX500 Cell Sorter 1 Laser (B)",
  "Sony FX500 Cell Sorter 2 Laser (B/R)",
  "Sony FX500 Cell Sorter 2 Laser (B/Yg)",
  "Sony FX500 Cell Sorter 3 Laser (B/R/Yg)",
  "Sony MA900 Cell Sorter 2 Laser (B/R)",
  "Sony MA900 Cell Sorter 2 Laser (B/V)",
  "Sony MA900 Cell Sorter 3 Laser (B/R/V)",
  "Sony MA900 Cell Sorter 3 Laser (B/R/Yg)",
  "Sony MA900 Cell Sorter 3 Laser (B/V/Yg)",
  "Sony MA900 Cell Sorter 4 Laser (B/R/V/Yg)",
  "Sony SH800 Cell Sorter 1 Laser (B)",
  "Sony SH800 Cell Sorter 2 Laser (B/R)",
  "Sony SH800 Cell Sorter 2 Laser (B/V)",
  "Sony SH800 Cell Sorter 2 Laser (B/Yg)",
  "Sony SH800 Cell Sorter 3 Laser (B/R/V)",
  "Sony SH800 Cell Sorter 3 Laser (B/R/Yg)",
  "Sony SH800 Cell Sorter 3 Laser (B/V/Yg)",
  "Sony SH800 Cell Sorter 4 Laser (B/R/V/Yg)",
  "PerkinElmer Opera Phenix",
  "Bio-Rad S3e 3 laser (V/B/Y) 4 color",
  "IntelliCyt iQue 3 BR",
  "IntelliCyt iQue 3 VBR",
  "IntelliCyt iQue 3 VYB",
  "Custom Instrument",
];

export const fluorophoresData = [
  "10-Acetyl-37-dihydroxyphenoxazin",
  "2-NBDG",
  "4-MUP",
  "5-CFDA",
  "5-FAM",
  "5-TAMRA",
  "6-TAMRA",
  "7-AAD",
  "7-Amino-4-methylcoumarin (AMC)",
  "7C",
  "AccuClear",
  "AccuOrange",
  "Acridine Orange",
  "Agarose",
  "alamarBlue",
  "Aldefluor",
  "Alexa 488 NanoGold",
  "Alexa 546 NanoGold",
  "Alexa 594 NanoGold",
  "Alexa 647 NanoGold",
  "Alexa Fluor 350",
  "Alexa Fluor 405",
  "Alexa Fluor 430",
  "Alexa Fluor 488",
  "Alexa Fluor 488 NanoGold",
  "Alexa Fluor 514",
  "Alexa Fluor 532",
  "Alexa Fluor 546",
  "Alexa Fluor 555",
  "Alexa Fluor 568",
  "Alexa Fluor 594",
  "Alexa Fluor 610",
  "Alexa Fluor 633",
  "Alexa Fluor 635",
  "Alexa Fluor 647",
  "Alexa Fluor 660",
  "Alexa Fluor 680",
  "Alexa Fluor 700",
  "Alexa Fluor 750",
  "Alexa Fluor 790",
  "Alizarin Red",
  "Alk Phosphatase",
  "AMCA",
  "AmCyan",
  "AmCyan - Protein",
  "Amethyst Orange",
  "APC",
  "APC-Alexa 680",
  "APC-Alexa 700",
  "APC-Alexa 750",
  "APC-CF750",
  "APC-CF750T",
  "APC-CF770",
  "APC-Cy5.5",
  "APC-Cy7",
  "APC-eFluor 780",
  "APC-Fire 750",
  "APC-Fire 810",
  "APC-H7",
  "APC-R700",
  "APC-Vio770",
  "APF",
  "APTS",
  "ATTO 390",
  "ATTO 425",
  "ATTO 425 Phalloidin",
  "ATTO 465",
  "ATTO 488",
  "ATTO 532",
  "ATTO 532 Phalloidin",
  "ATTO 542",
  "ATTO 550",
  "ATTO 565",
  "ATTO 594",
  "ATTO 610",
  "ATTO 633",
  "ATTO 647",
  "ATTO 647N",
  "ATTO 655",
  "ATTO 655 Phalloidin",
  "ATTO 665",
  "ATTO 680",
  "ATTO 700",
  "ATTO RHO101",
  "ATTO Rho11",
  "ATTO Rho12",
  "ATTO Rho13",
  "ATTO Rho14",
  "ATTO Rho3B",
  "ATTO Rho6G",
  "BactoView Live Green",
  "BactoView Live Red",
  "BB515",
  "BB700",
  "BCECF",
  "BCECF (525em) pH9.0",
  "BCECF AM",
  "BCECF (Red em) pH5.2",
  "BDY 630-X SE",
  "BDY 650-X SE",
  "BDY FL SE",
  "BDY FL-X SE",
  "BDY TMR-X SE",
  "BDY TR-X SE",
  "Beta Gal",
  "BFP",
  "BIMA",
  "Biotin",
  "BOBO-1",
  "BOBO-3",
  "BODIPY 493/503",
  "BODIPY 500/510",
  "BODIPY 558/568",
  "BODIPY 581/591",
  "BODIPY 630/650",
  "BODIPY 650/665",
  "BODIPY FL",
  "BODIPY R6G",
  "BODIPY TMR-X",
  "BODIPY TR",
  "BPE",
  "Brilliant Violet 421",
  "Brilliant Violet 480",
  "Brilliant Violet 510",
  "Brilliant Violet 570",
  "Brilliant Violet 605",
  "Brilliant Violet 650",
  "Brilliant Violet 711",
  "Brilliant Violet 750",
  "Brilliant Violet 785",
  "Brilliant Violet 786",
  "BUV395",
  "BUV496",
  "BUV563",
  "BUV615",
  "BUV661",
  "BUV737",
  "BUV805",
  "Calcein",
  "Calcein AM",
  "Calcein Blue",
  "Calcein Blue AM",
  "Calcein Deep Red",
  "Calcein Deep Red AM",
  "Calcein Green",
  "Calcein Orange",
  "Calcein Red",
  "Calcein Red AM",
  "Calcein Red-Orange AM",
  "Calcein Violet AM",
  "Calcium Crimson (Ca2+bound)",
  "Calcium Green",
  "Calcium Orange",
  "California Red",
  "Carboxyfluorescein",
  "Cascade Blue",
  "Cascade Yellow",
  "CellBrite Blue",
  "CellBrite Fix 488",
  "CellBrite Fix 555",
  "CellBrite Fix 640",
  "CellBrite Green",
  "CellBrite NIR680",
  "CellBrite NIR750",
  "CellBrite NIR770",
  "CellBrite NIR790",
  "CellBrite Orange",
  "CellBrite Red",
  "CellBrite Steady 405",
  "CellBrite Steady 488",
  "CellBrite Steady 550",
  "CellBrite Steady 650",
  "CellBrite Steady 685",
  "CellMask Deep Red Plasma Membrane Stain",
  "CellMask Orange Plasma Membrane Stain",
  "CellROX Deep Red",
  "CellROX Green",
  "CellROX Orange",
  "CellTrace Blue",
  "CellTrace CFSE",
  "CellTrace Far Red",
  "CellTrace Oregon Green",
  "CellTrace Violet",
  "CellTrace Yellow",
  "CellTracker Blue",
  "CellTracker Deep Red",
  "CellTracker Orange",
  "CellTracker Red",
  "CellTracker Violet",
  "CellVue Burgundy",
  "CellVue Jade",
  "CellVue Lavender",
  "CellVue Maroon",
  "CellVue NIR780",
  "CellVue Plum",
  "Cerulean",
  "CF350",
  "CF405L",
  "CF405M",
  "CF405S",
  "CF408",
  "CF430",
  "CF440",
  "CF450",
  "CF488A",
  "CF5",
  "CF500",
  "CF503R",
  "CF514",
  "CF517ST",
  "CF532",
  "CF535ST",
  "CF540",
  "CF543",
  "CF550R",
  "CF555",
  "CF568",
  "CF568ST",
  "CF570",
  "CF583",
  "CF583R",
  "CF594",
  "CF594ST",
  "CF620R",
  "CF633",
  "CF640R",
  "CF647",
  "CF647ST",
  "CF650",
  "CF660C",
  "CF660R",
  "CF660ST",
  "CF680",
  "CF680R",
  "CF680ST",
  "CF680T",
  "CF700",
  "CF750",
  "CF750ST",
  "CF770",
  "CF770T",
  "CF790",
  "CF800",
  "CF820",
  "CFP",
  "CFSE",
  "Chromeo 488",
  "Chromeo 494",
  "Chromeo 505",
  "Chromeo 546",
  "Chromeo 642",
  "CMA-Chromomycin A3",
  "CoraLite 488",
  "CoraLite 594",
  "CoraLite 647",
  "CPN475 Blue",
  "CPN510 Green",
  "CPN550 Yellow",
  "CPN680 Red",
  "Cy2",
  "Cy3",
  "Cy3.5",
  "Cy5",
  "Cy5.5",
  "Cy7",
  "Cyanine 3 SE",
  "Cyanine 555",
  "Cyanine 5 SE",
  "Cyanine 647",
  "Cyanine 7 SE",
  "CypHer5E",
  "CytoCalcein Violet 450",
  "CytoCalcein Violet 500",
  "CYTO-ID Green",
  "CYTO-ID Green Cell Trace",
  "CYTO-ID Red Cell Trace",
  "CytoTrace Green CMFDA",
  "CytoTrace Red",
  "CytoTrack Blue",
  "CytoTrack Green",
  "CytoTrack Red",
  "CytoTrack Yellow",
  "CyTRAK Orange",
  "DAF-FM",
  "Dansyl",
  "DAPI",
  "DCF",
  "Di-8-ANEPPS",
  "DiD",
  "DiFMU pH3.0",
  "DiFMU pH9.0",
  "Dihydroethidium",
  "DiI",
  "DiIC1(5)",
  "DiO",
  "DiR",
  "DMAO",
  "DRAQ 5",
  "DRAQ 7",
  "DRAQ 9",
  "dsRed",
  "DsRed2",
  "DsRed Express",
  "dTomato",
  "DY-350XL",
  "DY-350XL Phalloidin",
  "DY-360XL",
  "DY-360XL Phalloidin",
  "DY-370XL",
  "DY-370XL Phalloidin",
  "DY-375XL",
  "DY-375XL Phalloidin",
  "DY-380XL",
  "DY-380XL Phalloidin",
  "DY-395XL",
  "DY-395XL Phalloidin",
  "DY-415",
  "DY-415 Phalloidin",
  "DY-480XL",
  "DY-481XL",
  "DY-485XL",
  "DY-510XL",
  "DY-511XL",
  "DY-520XL",
  "DY-521XL",
  "DY-547 Phalloidin",
  "DY-601XL",
  "DyLight 350",
  "DyLight 405",
  "DyLight 405LS",
  "DyLight 488",
  "DyLight 549",
  "DyLight 550",
  "DyLight 594",
  "DyLight 633",
  "DyLight 649",
  "DyLight 650",
  "DyLight 680",
  "DyLight 750",
  "DyLight 755",
  "DyLight 800",
  "Dyomics 547",
  "Dyomics 590",
  "Dyomics 647",
  "E2-Crimson",
  "eBFP",
  "ECD",
  "eCFP",
  "eFluor 450",
  "eFluor 450 Cell Proliferation",
  "eFluor 450 Fix Viability",
  "eFluor 455UV Fix Viability",
  "eFluor 506",
  "eFluor 506 Fix Viability",
  "eFluor 514 Calcium Sensor",
  "eFluor 520 Fix Viability",
  "eFluor 565NC",
  "eFluor 570",
  "eFluor 585NC",
  "eFluor 605NC",
  "eFluor 615",
  "eFluor 625NC",
  "eFluor 650NC",
  "eFluor 660",
  "eFluor 660 Fix Viability",
  "eFluor 670 Cell Proliferation",
  "eFluor 710",
  "eFluor 780 Fix Viability",
  "EFLUXX-ID Gold",
  "EFLUXX-ID Green",
  "eGFP",
  "EMA",
  "Emerald GFP",
  "ENZO Gold",
  "ER-ID Green",
  "ER-ID Red",
  "Ethidium B.",
  "Ethidium Homodimer I",
  "Ethidium Homodimer III",
  "EvaGreen",
  "EvaGreen Plus",
  "eVolve 605",
  "eVolve 655",
  "eYFP",
  "FAM",
  "FDG",
  "FITC",
  "FlAsH",
  "Flash Phalloidin Green 488",
  "Flash Phalloidin NIR 647",
  "Flash Phalloidin Red 594",
  "Fluo-3",
  "Fluo-3 AM",
  "Fluo-4",
  "Fluo-4 AM",
  "FLUOFORTE",
  "FluoProbes647H",
  "Fluorescein",
  "Fluorescein-NanoGold",
  "Fluoro-Gold",
  "Fura-2 (Ca2+bound)",
  "Fura-2 (Ca2+free)",
  "Fura Red AM (Ca2+bound)",
  "Fura Red AM (Ca2+free)",
  "FVS440UV",
  "FVS450",
  "FVS510",
  "FVS520",
  "FVS570",
  "FVS575V",
  "FVS620",
  "FVS660",
  "FVS700",
  "FVS780",
  "FxCycle Far Red",
  "FxCycle Violet",
  "GelGreen",
  "GelRed",
  "GFP",
  "Ghost Dye Blue 516",
  "Ghost Dye Red 710",
  "Ghost Dye Red 780",
  "Ghost Dye UV 450",
  "Ghost Dye Violet 450",
  "Ghost Dye Violet 510",
  "Ghost Dye Violet 540",
  "GOLGI-ID Green",
  "Hc Red",
  "Helix NP NIR",
  "HiLyte 405",
  "HiLyte 488",
  "HiLyte 555",
  "HiLyte 594",
  "HiLyte 647",
  "HiLyte 750",
  "Hoechst (33258)",
  "Hoechst (33342)",
  "Hoechst (34580)",
  "HRP",
  "Hydroxystilbamidine",
  "iFluor 350",
  "iFluor 405",
  "iFluor 488",
  "iFluor 514",
  "iFluor 532",
  "iFluor 555",
  "iFluor 594",
  "iFluor 633",
  "iFluor 647",
  "iFluor 680",
  "iFluor 700",
  "iFluor 750",
  "iFluor 790",
  "IFP 1.4",
  "Indocyanine Green",
  "Indo-Hi (Ca2+bound)",
  "Indo-Lo (Ca2+free)",
  "IRDye 650",
  "IRDye 680LT",
  "IRDye 680RD",
  "IRDye 800CW",
  "iRFP",
  "iRFP 670",
  "iRFP 682",
  "iRFP 702",
  "iRFP 713",
  "iRFP 720",
  "Janelia Fluor 525",
  "Janelia Fluor 549",
  "Janelia Fluor 585",
  "Janelia Fluor 635",
  "Janelia Fluor 646",
  "Janelia Fluor 669",
  "JC-1",
  "Kaede (green)",
  "Kaede (red)",
  "Katushka2S",
  "KikGR1 (green)",
  "KikGR1 (red)",
  "KIRAVIA Blue 520",
  "Krome Orange",
  "LDS 751",
  "LipidSpot 488",
  "LipidSpot 610",
  "Live/Dead Fix Aqua",
  "Live/Dead Fix Blue",
  "Live/Dead Fix Far Red",
  "Live/Dead Fix Green",
  "Live/Dead Fix Near IR",
  "Live/Dead Fix Red",
  "Live/Dead Fix Violet",
  "Live/Dead Fix Yellow",
  "Live-or-Dye 350/448",
  "Live-or-Dye 375/600",
  "Live-or-Dye 405/452",
  "Live-or-Dye 405/545",
  "Live-or-Dye 488/515",
  "Live-or-Dye 510/550",
  "Live-or-Dye 568/583",
  "Live-or-Dye 594/614",
  "Live-or-Dye 615/740",
  "Live-or-Dye 640/662",
  "Live-or-Dye 665/685",
  "Live-or-Dye 750/777",
  "Live-or-Dye 787/808",
  "Live-or-Dye NucFix Red",
  "LSS-mKate1",
  "LSS-mKate2",
  "LSSmOrange",
  "Lucifer Yellow",
  "Lucigenin",
  "Luminol",
  "LysoBrite Blue",
  "LysoBrite Deep Red",
  "LysoBrite Green",
  "LysoBrite NIR",
  "LysoBrite Orange",
  "LysoBrite Red",
  "LYSO-ID Green",
  "LysoSensor Yellow/Blue pH3.0",
  "LysoSensor Yellow/Blue pH9.0",
  "LysoTracker Green",
  "LysoView 405",
  "LysoView 488",
  "LysoView 540",
  "LysoView 633",
  "LysoView 650",
  "Mag-Fura-2",
  "Magic Red",
  "Malachite Green",
  "Malachite Green 2p",
  "mAmetrine",
  "mApple",
  "Marina Blue",
  "MaxLight 405",
  "MaxLight 490",
  "MaxLight 550",
  "MaxLight 650",
  "MaxLight 750",
  "mBanana",
  "mBBR",
  "mBCl",
  "mCerulean3",
  "mCherry",
  "mCitrine",
  "MemBrite Fix 405/430",
  "MemBrite Fix 488/515",
  "MemBrite Fix 543/560",
  "MemBrite Fix 568/580",
  "MemBrite Fix 594/615",
  "MemBrite Fix 640/660",
  "MemBrite Fix 660/680",
  "MemBrite Fix 680/700",
  "MemBrite Fix ST 650/665",
  "MemBrite Fix ST 667/685",
  "MemBrite Fix ST 681/698",
  "MemBrite Fix ST 755/777",
  "mFluor 450",
  "mFluor 540",
  "mHoneyDew",
  "MiCy1",
  "MITO-ID (Extracellular O2)",
  "MITO-ID Green",
  "MITO-ID MP (high potential)",
  "MITO-ID Red",
  "MitoLite Blue FX490",
  "MitoLite Deep Red FX660",
  "MitoLite Green EX488",
  "MitoLite Green FM",
  "MitoLite NIR FX690",
  "MitoLite Orange EX405",
  "MitoLite Orange FX570",
  "MitoLite Red FX600",
  "MitoMark Green",
  "MitoMark Red",
  "MitoROS 520",
  "MitoSOX Red",
  "MitoSpy Green",
  "MitoSpy NIR",
  "MitoSpy Orange",
  "MitoSpy Red",
  "MitoTracker CMXRos Red",
  "MitoTracker Deep Red",
  "MitoTracker Green",
  "MitoTracker Orange",
  "MitoTracker Red",
  "MitoView 405",
  "MitoView 633",
  "MitoView 650",
  "MitoView 720",
  "MitoView Blue",
  "MitoView Green",
  "mKate",
  "mKate2",
  "mKeima",
  "mKO",
  "mKusabira-Orange2",
  "mNeptune",
  "Monobromobimane",
  "mOrange",
  "mPlum",
  "mRaspberry",
  "mRFP1",
  "mRuby",
  "mStrawberry",
  "mTangerine",
  "mTurquoise",
  "NADH",
  "NBD",
  "NBD-X",
  "Neuro DiO",
  "NeuroVue Burgundy",
  "NeuroVue Jade",
  "NeuroVue Maroon",
  "NeuroVue Orange",
  "NeuroVue Red",
  "Newport Green DCF",
  "Nile Blue",
  "Nile Red",
  "NirFP",
  "NL 493",
  "NL 557",
  "NL 637",
  "NovaBlue 510",
  "NovaBlue 530",
  "NovaBlue 555",
  "NovaBlue 610 / 30S",
  "NovaBlue 610 / 70S",
  "NovaBlue 660 / 120S",
  "NovaBlue 660 / 40S",
  "NovaRed 660",
  "NovaRed 685",
  "NovaRed 700",
  "NovaYellow 570",
  "NovaYellow 610",
  "NovaYellow 660",
  "NovaYellow 690",
  "NovaYellow 700",
  "Nuclear Blue",
  "Nuclear Green",
  "Nuclear-ID Blue",
  "Nuclear-ID Green",
  "Nuclear-ID Red",
  "Nuclear Orange",
  "Nuclear Red",
  "Nuclear Violet",
  "Nuclear Yellow",
  "Nucleolar-ID Green",
  "NucSpot 470",
  "NucSpot Far-Red",
  "NucSpot Live 488",
  "NucSpot Live 650",
  "NucView 405",
  "NucView 488",
  "NucView 530",
  "OC515",
  "OFP",
  "Oregon Green 488",
  "Oregon Green 488 BAPTA",
  "Oregon Green 514",
  "Oxazole Blue",
  "Oxazole Yellow",
  "Oyster 488",
  "Oyster 550",
  "Oyster 650",
  "Oyster 680",
  "P3",
  "Pacific Blue",
  "Pacific Green",
  "Pacific Orange",
  "PE",
  "PE-594",
  "PE-665",
  "PE-695",
  "PE-777",
  "PE-Alexa 610",
  "PE-Alexa 647",
  "PE-Alexa 700",
  "PE-Alexa 750",
  "PE-ATTO 594",
  "PE-CF594",
  "PE-Cy5",
  "PE-Cy5.5",
  "PE-Cy7",
  "PE-Dazzle 594",
  "PE-DyLight 594",
  "PE-Dyomics 590",
  "PE-Dyomics 647",
  "PE-eFluor 610",
  "PE-Fire 640",
  "PE-Fire 700",
  "PE-Fire 780",
  "PerCP",
  "PerCP-Cy5",
  "PerCP-Cy5.5",
  "PerCP-eFluor 710",
  "PerCP-Vio700",
  "PE-Texas Red",
  "PE-Vio615",
  "PE-Vio770",
  "Phalloidin-eFluor 520",
  "Phalloidin-eFluor 570",
  "Phalloidin-eFluor 660",
  "Phalloidin-TFAX 488",
  "PhenoVue 493 Lipid Stain",
  "PhenoVue 512 Nucleic Acid Stain",
  "PhenoVue 551 Mitochondrial Stain",
  "PhenoVue 578 Mitochondrial Stain",
  "PhenoVue 641 Mitochondrial Stain",
  "PhenoVue Fluor 488",
  "PhenoVue Fluor 555",
  "PhenoVue Fluor 568",
  "PhenoVue Fluor 594",
  "PhenoVue Hoechst 33342 Nuclear Stain",
  "PhenoVue Nile Red Lipid Stain",
  "pHrodo Green",
  "pHrodo Red",
  "PI",
  "PKH26",
  "PKH67",
  "PMA",
  "PMAxx",
  "POPO-1",
  "POPO-3",
  "Premo Cameleon Calcium Sensor (Ca2+ bound)",
  "Premo Cameleon Calcium Sensor (Ca2+ free)",
  "PromoFluor 350",
  "PromoFluor 405",
  "PromoFluor 488P",
  "PromoFluor 555P",
  "PromoFluor 594",
  "PromoFluor 633P",
  "PromoFluor 647P",
  "PromoFluor 680",
  "PromoFluor 750",
  "PromoFluor 780",
  "PromoFluor 840",
  "PROTEOSTAT-Red",
  "Protoporphyrin IX",
  "Purified",
  "Pyronin Y",
  "Qdot 525",
  "Qdot 545",
  "Qdot 565",
  "Qdot 585",
  "Qdot 605",
  "Qdot 625",
  "Qdot 655",
  "Qdot 705",
  "Qdot 800",
  "Quantum Red",
  "ReadiLink 405-454",
  "ReadiLink 405-508",
  "ReadiLink 405-537",
  "ReadiLink 492-516",
  "ReadiLink 555-570",
  "ReadiLink 594-610",
  "ReadiLink 633-655",
  "ReadiLink 647-674",
  "ReadiLink 680-701",
  "ReadiLink 700-713",
  "ReadiLink 750-780",
  "ReadiLink 790-811",
  "ReAsH",
  "Red 718",
  "RedDot 1",
  "RedDot 2",
  "redFluor 710",
  "Red Necrosis Stain",
  "Resazurin",
  "Resorufin",
  "RFP",
  "Rhod-2 (Ca2+ bound)",
  "Rhod-5N (Ca2+ bound)",
  "Rhodamine",
  "Rhodamine 101",
  "Rhodamine 110",
  "Rhodamine 123",
  "Rhodamine 6G",
  "Rhodamine B",
  "Rhodamine Green",
  "Rhodamine-phalloidin",
  "Rhodamine Red",
  "Rhodamine Red-X",
  "Rhod-FF",
  "Rhod-FF AM",
  "Riboflavin",
  "ROS",
  "Rose Bengal",
  "ROS-ID Green",
  "ROS-ID Orange",
  "ROS-ID Red",
  "RPC",
  "RPE-CF583R",
  "RPE-CF647T",
  "Saporin",
  "SBFI",
  "Sepharose",
  "Seta-385-NHS",
  "Seta-400-NHS",
  "Seta-555-NHS",
  "Seta-650-NHS",
  "Seta-680-NHS",
  "Seta-750-NHS",
  "Seta-APC-705",
  "Seta-APC-780",
  "Seta-PerCP-680",
  "Seta-R-PE-670",
  "Seta-R-PE-775",
  "SeTau-647-di-NHS",
  "SeTau-647-NHS",
  "SeTau-665-NHS",
  "SeTau-670-NHS",
  "SeTau-680-NHS",
  "SNARF 1 pH6.0",
  "SNARF 1 pH9.0",
  "Spark Blue 550",
  "Spark NIR 685",
  "Spark Violet 538",
  "Spark YG 570",
  "Spectral Red",
  "Spectrum Aqua",
  "Spectrum Green",
  "SPQ",
  "STAR 440SXP",
  "STAR 470SXP",
  "STAR 488",
  "STAR 512",
  "STAR 520SXP",
  "STAR 580",
  "STAR 600",
  "STAR 635",
  "STAR 635P",
  "StarBright Blue 520",
  "StarBright Blue 700",
  "StarBright Violet 440",
  "StarBright Violet 475",
  "StarBright Violet 515",
  "StarBright Violet 570",
  "StarBright Violet 610",
  "StarBright Violet 670",
  "StarBright Violet 710",
  "StarBright Violet 760",
  "StarBright Violet 790",
  "STAR GREEN",
  "STAR ORANGE",
  "STAR RED",
  "Sulforhodamine 101",
  "SuperBright 436",
  "SuperBright 600",
  "SuperBright 645",
  "SuperBright 702",
  "SuperBright 780",
  "SuperNova v428",
  "SuperNova v605",
  "SuperNova v786",
  "SureLight 488",
  "SYBR Green",
  "Synapto Green",
  "Synapto Red",
  "Syto 16",
  "Syto 61",
  "Syto 9",
  "Sytox AADvanced",
  "Sytox Blue",
  "Sytox Deep Red",
  "Sytox Green",
  "Sytox Orange",
  "Sytox Red",
  "TagBFP",
  "Tag-It Violet",
  "TagRFP",
  "TagRFP657",
  "tdTomato",
  "Texas Red",
  "TFAX 488 SE",
  "TFAX 488 TFP",
  "TFAX 546 SE",
  "TFAX 568 SE",
  "TFAX 594 SE",
  "TFP",
  "Thiazole Orange",
  "Thiazole Orange Homodimer",
  "Thiazole Orange Iodide",
  "Thiazole Red",
  "Thiazole Red Homodimer",
  "TMA-DPH",
  "TMRE",
  "Topaz",
  "TO-Pro 1",
  "TO-Pro 3",
  "TOTO-1",
  "TOTO-3",
  "Tri-Color",
  "TRITC",
  "T-Sapphire",
  "V450",
  "V500",
  "Venus",
  "ViaFluor 405",
  "ViaFluor 488",
  "ViaFluor 568",
  "Viafluor CFSE",
  "ViaKrome 405",
  "ViaKrome 561",
  "ViaKrome 638",
  "ViaKrome 808",
  "Vio488",
  "Vio515",
  "Vio667",
  "Viobility 405/452 Fixable Dye",
  "Viobility 405/520 Fixable Dye",
  "Viobility 488/520 Fixable Dye",
  "VioBlue",
  "VioBright 515",
  "VioBright 667",
  "VioBright FITC",
  "Vio Bright R667",
  "Vio Bright R720",
  "Vio Bright V423",
  "VioGreen",
  "violetFluor 450",
  "violetFluor 500",
  "Vio R667",
  "Vio R720",
  "VivaFix 353/442",
  "VivaFix 398/550",
  "VivaFix 408/512",
  "VivaFix 410/450",
  "VivaFix 498/521",
  "VivaFix 547/573",
  "VivaFix 583/603",
  "VivaFix 649/660",
  "VivoTag 645",
  "VivoTag 680-XL",
  "VivoTag S680",
  "VPD450",
  "VRDye 490",
  "VRDye 549",
  "Vybrant DyeCycle Green",
  "Vybrant DyeCycle Orange",
  "Vybrant DyeCycle Ruby",
  "Vybrant DyeCycle Violet",
  "X-Rhod-1 (Ca2+ bound)",
  "X-Rhod-5F (Ca2+ bound)",
  "YFP",
  "YO-PRO-1",
  "YO-PRO-3",
  "YOYO-1",
  "YOYO-3",
  "Zinquin",
  "Zombie Aqua",
  "Zombie Green",
  "Zombie NIR",
  "Zombie Red",
  "Zombie UV",
  "Zombie Violet",
  "Zombie Yellow",
  "ZsGreen",
];

// export const sectionList = [
//   {
//     id: 1,
//     name: "device",
//     label: "To optimize analysis please select your Device",
//     dataList: machinesData,
//     placeholder: "Please select a device",
//     optKey: "device",
//   },
//   {
//     id: 2,
//     name: "cell_type",
//     label: "What is the cell type are you measuring?",
//     dataList: cellTypeList,
//     placeholder: "Please select a Cell Type",
//     optKey: "cell_type",
//   },
//   {
//     id: 3,
//     name: "particles_size",
//     label: "How big are the particles you are measuring?",
//     dataList: particlesSizeList,
//     placeholder: "Please select a Particle Size",
//     optKey: "particles_size",
//   ,
//   {
//     id: 4,
//     name: "fluorophores",
//     label: "Select the fluorophores in your analysis",
//     dataList: fluorophoresData,
//     placeholder: "Please select a fluorophores",
//     optKey: "fluorophores",
//   ,
// ];
