export const actionTypes = {
  RESET: "RESET",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  EXPERIMENT_FORM_DATA: "EXPERIMENT_FORM_DATA",
  CHANGE_SUBSCRIPTION_TYPE: "CHANGE_SUBSCRIPTION_TYPE",
  EXPERIMENT_FORM_DATA_CLEAR: "EXPERIMENT_FORM_DATA_CLEAR",
  UPDATE_SUBSCRIPTION_DETAILS: "UPDATE_SUBSCRIPTION_DETAILS",
};
