export const actionTypes = {
  RESET: "RESET",

  // Macro
  LOAD_WORKSPACE: "LOAD_WORKSPACE",
  SET_EXPERIMENT_METADATA: "SET_EXPERIMENT_METADATA",

  // Creators
  ADD_FILE: "ADD_FILE",
  ADD_PLOT: "ADD_PLOT",
  ADD_GATE: "ADD_GATE",

  DUPLICATE_PLOT: "DUPLICATE_PLOT",
  DUPLICATE_GATE: "DUPLICATE_GATE",
  SUBPOP_FROM_GATE: "SUBPOP_FROM_GATE",
  ADD_GATE_TO_ALL_FILES: "ADD_GATE_TO_ALL_FILES",

  // Linkers
  LINK_GATE_TO_PLOT: "LINK_GATE_TO_PLOT",
  UNLINK_GATE_TO_PLOT: "UNLINK_GATE_TO_PLOT",

  // Destroyers
  REMOVE_GATE_FROM_WORKSPACE: "REMOVE_GATE_FROM_WORKSPACE",
  REMOVE_PLOT_FROM_WORKSPACE: "REMOVE_PLOT_FROM_WORKSPACE",
  REMOVE_FILE_FROM_WORKSPACE: "REMOVE_FILE_FROM_WORKSPACE",

  // Minor
  RANGE_CHANGE: "RANGE_CHANGE",
  MOUSE_EVENT: "MOUSE_EVENT",
  GATE_METADATA_UPDATE: "GATE_METADATA_UPDATE",
};
