/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body5
 */
export interface Body5 {
    /**
     * Graph Name
     * @type {string}
     * @memberof Body5
     */
    graphName?: any;
    /**
     * Workspace Id
     * @type {string}
     * @memberof Body5
     */
    workspaceId?: any;
    /**
     * Send the updated graph object
     * @type {any}
     * @memberof Body5
     */
    graphChanges?: any;
}
