/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body4
 */
export interface Body4 {
    /**
     * 
     * @type {string}
     * @memberof Body4
     */
    workspaceId?: any;
    /**
     * 
     * @type {string}
     * @memberof Body4
     */
    organisationId?: any;
    /**
     * 
     * @type {string}
     * @memberof Body4
     */
    file0?: any;
}
