/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body3
 */
export interface Body3 {
    /**
     * Organisation Id
     * @type {string}
     * @memberof Body3
     */
    organisationId?: any;
    /**
     * Name of workspace
     * @type {string}
     * @memberof Body3
     */
    name?: any;
    /**
     * private or public workspace
     * @type {boolean}
     * @memberof Body3
     */
    isPrivate?: any;
}
