/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body6
 */
export interface Body6 {
    /**
     * 
     * @type {string}
     * @memberof Body6
     */
    graphName?: any;
    /**
     * 
     * @type {string}
     * @memberof Body6
     */
    workspaceId?: any;
}
