/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GatingCoords
 */
export interface GatingCoords {
    /**
     * 
     * @type {number}
     * @memberof GatingCoords
     */
    x?: any;
    /**
     * 
     * @type {number}
     * @memberof GatingCoords
     */
    y?: any;
}
