/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2002Workspaces
 */
export interface InlineResponse2002Workspaces {
    /**
     * workspace id
     * @type {string}
     * @memberof InlineResponse2002Workspaces
     */
    id?: any;
    /**
     * workspace name
     * @type {string}
     * @memberof InlineResponse2002Workspaces
     */
    name?: any;
    /**
     * workspace created date
     * @type {string}
     * @memberof InlineResponse2002Workspaces
     */
    createdOn?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2002Workspaces
     */
    isOwner?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2002Workspaces
     */
    isPrivate?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2002Workspaces
     */
    noAccepted?: any;
    /**
     * Email of user
     * @type {string}
     * @memberof InlineResponse2002Workspaces
     */
    owner?: any;
}
