/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003
     */
    location?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003
     */
    token?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003
     */
    organisationId?: any;
}
