/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    token?: any;
    /**
     * experiment id
     * @type {string}
     * @memberof InlineResponse2007
     */
    id?: any;
    /**
     * 
     * @type {ExperimentDetailView}
     * @memberof InlineResponse2007
     */
    details?: any;
    /**
     * experiment data
     * @type {any}
     * @memberof InlineResponse2007
     */
    data?: any;
}
