/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2009Files
 */
export interface InlineResponse2009Files {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009Files
     */
    createdOn?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009Files
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009Files
     */
    label?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009Files
     */
    workspaceId?: any;
}
