/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2009Spillover
 */
export interface InlineResponse2009Spillover {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof InlineResponse2009Spillover
     */
    spilloverParamLabels?: any;
    /**
     * 
     * @type {Array&lt;Array&lt;string&gt;&gt;}
     * @memberof InlineResponse2009Spillover
     */
    spilloverValues?: any;
}
