/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2009
 */
export interface InlineResponse2009 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009
     */
    workspaceName?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009
     */
    version?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009
     */
    token?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009
     */
    path?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2009
     */
    numParams?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009
     */
    label?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2009
     */
    eventCount?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2009
     */
    eventWarning?: any;
    /**
     * 
     * @type {InlineResponse2009Analysis}
     * @memberof InlineResponse2009
     */
    analysis?: any;
    /**
     * 
     * @type {Array&lt;InlineResponse2009Files&gt;}
     * @memberof InlineResponse2009
     */
    files?: any;
    /**
     * 
     * @type {Array&lt;InlineResponse2009Params&gt;}
     * @memberof InlineResponse2009
     */
    params?: any;
    /**
     * 
     * @type {InlineResponse2009Spillover}
     * @memberof InlineResponse2009
     */
    spillover?: any;
    /**
     * 
     * @type {any}
     * @memberof InlineResponse2009
     */
    text?: any;
}
