/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse200UserDetails
 */
export interface InlineResponse200UserDetails {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200UserDetails
     */
    organisationId?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200UserDetails
     */
    availableUntil?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200UserDetails
     */
    totalNumFilesPaidFor?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200UserDetails
     */
    totalFilesUploaded?: any;
}
