/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2008
 */
export interface InlineResponse2008 {
    /**
     * Name of workspace
     * @type {string}
     * @memberof InlineResponse2008
     */
    workspaceName?: any;
    /**
     * number of files remaining for user
     * @type {number}
     * @memberof InlineResponse2008
     */
    filesRemaining?: any;
    /**
     * Exp. Date of workspace
     * @type {string}
     * @memberof InlineResponse2008
     */
    availableUntil?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2008
     */
    monthlyFileCounter?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2008
     */
    isOwner?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2008
     */
    token?: any;
    /**
     * 
     * @type {Array&lt;InlineResponse2008Files&gt;}
     * @memberof InlineResponse2008
     */
    files?: any;
}
