/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2009Params
 */
export interface InlineResponse2009Params {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009Params
     */
    display?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2009Params
     */
    key?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009Params
     */
    value?: any;
}
