/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2009Analysis
 */
export interface InlineResponse2009Analysis {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2009Analysis
     */
    fCSVersion?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2009Analysis
     */
    beginAnalysis?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2009Analysis
     */
    beginData?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2009Analysis
     */
    beginText?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2009Analysis
     */
    endAnalysis?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2009Analysis
     */
    endData?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2009Analysis
     */
    endText?: any;
}
