/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20011
 */
export interface InlineResponse20011 {
    /**
     * 
     * @type {Array&lt;any&gt;}
     * @memberof InlineResponse20011
     */
    fileIds?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20011
     */
    graphName?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20011
     */
    isDotPlot?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20011
     */
    paramX?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20011
     */
    paramY?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20011
     */
    selectedGate?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20011
     */
    xScale?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20011
     */
    yScale?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20011
     */
    height?: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20011
     */
    width?: any;
}
