/* tslint:disable */
/* eslint-disable */
/**
 * Red Matter
 * API configuration
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004
     */
    token?: any;
    /**
     * Workspace id
     * @type {string}
     * @memberof InlineResponse2004
     */
    id?: any;
    /**
     * Workspace name
     * @type {string}
     * @memberof InlineResponse2004
     */
    name?: any;
    /**
     * Workspace creation date
     * @type {string}
     * @memberof InlineResponse2004
     */
    createdOn?: any;
}
