export default [
  {
    name: "California Polytechnic State University.png",
  },
  { name: "Thomas Jefferson University.jpg" },
  { name: "University of California San Francisco.png" },
  { name: "University of Cambridge.jpg" },
  { name: "Long Island University.png" },
  { name: "University of Edinburgh.png" },
  { name: "University of Pittsburgh.png" },
  { name: "University of Copenhagen.png" },
  { name: "Karolinska Institutet.png" },
  { name: "Universidad de los Andes.jpg" },
  { name: "Monash University.png" },
  { name: "University of California San Diego.png" },
  { name: "University of Toronto.png" },
  { name: "Linköpings Universitet.png" },
  { name: "University of Michigan.png" },
  { name: "National Autonomous University of Mexico.png" },
  { name: "University of Oxford.svg" },
  { name: "Inserm (France).jpg" },
  { name: "CNRS (France).png" },
  { name: "University of Minnesota.png" },
  { name: "University of Manchester.png" },
  { name: "University of Ottawa.png" },
  { name: "UCLA.png" },
  { name: "UNB.png" },
  { name: "University of Basel.jpg" },
  { name: "University of Sao Paulo.jpg" },
  { name: "Instituto de Medicina Tropical de São Paulo.png" },
  { name: "Universidade de Campinas.png" },
  { name: "Yale University.png" },
  { name: "University of Pennsylvania.png" },
  { name: "University of Birmingham.jpg" },
  { name: "University of Leicester.png" },
  { name: "Columbia University.png" },
  { name: "Tel Aviv university.png" },
  { name: "Duke University.png" },
  { name: "Johns Hopkins.png" },
  { name: "MIT.png" },
  // { name: "Seoul National University.jpg" },
  { name: "University of Sydney.png" },
  { name: "The Hebrew University of Jerusalem.png" },
  { name: "The University of Hong Kong.png" },
  { name: "Osaka university.png" },
  { name: "Université de Montréal.png" },

  // { name: "Ludwig Maximilian University of Munich",  },
  // { name: "UCL (London)",  },
  // { name: "Cardiff University",  },
  // { name: "University of Cincinnati",  },
  // { name: "Newcastle University",  },
  // { name: "Stanford University",  },
  // { name: "Mayo Clinic",  },
  // { name: "University of Florida",  },
  // { name: "UC Berkeley",  },
  // { name: "University of Sheffield",  },
  // { name: "King's College London",  },
  // { name: "Imperial College London",  },
  // { name: "University College London",  },
  // { name: "University of Iowa",  },
  // { name: "Emory University",  },
  // { name: "Dalhousie University",  },
  // { name: "Broad Institute",  },
  // { name: "UAB",  },
  // { name: "CINVESTAV (Mexico)",  },
  // { name: "Trinity College Dublin",  },
  // { name: "National University of Singapore",  },
  // { name: "Northwestern University",  },
  // { name: "University of Illinois",  },
  // { name: "University of Dundee",  },
  // { name: "Jagiellonian University (Poland)",  },
  // { name: "Linköping University",  },
  // { name: "UCD",  },
  // { name: "University of glasgow",  },
  // { name: "University of Oregon",  },
  // { name: "University of Nottingham",  },
  // { name: "Freie Universität Berlin",  },
  // { name: "UBC",  },
  // { name: "University of Perugia",  },
  // { name: "HKU",  },
  // { name: "NUS",  },
  // { name: "DRFZ",  },
  // { name: "MSKCC",  },
  // { name: "University of Vienna",  },
  // { name: "Baylor College of Medicine",  },
  // { name: "Albert Einstein College of Medicine",  },
  // { name: "University of British Columbia",  },
  // { name: "German Cancer Research Center",  },
  // { name: "Boston Children's Hospital",  },
  // { name: "Penn State College of Medicine",  },
  // { name: "Cincinnati Children's Hospital",  },
  // { name: "University of Twente",  },
  // { name: "Children's Hospital of Philadelphia",  },
  // { name: "Mount Sinai Hospital",  },
  // { name: "Dana Farber Cancer Institute",  },
  // { name: "Purdue University",  },
  // { name: "BSRC Alexander Fleming",  },
  // { name: "Research Center Borstel",  },
  // {
  //   name: "Landspítali - The National University Hospital of Iceland",
  //   ,
  // },
  // { name: "University of Groningen",  },
  // { name: "University of Lausanne",  },
  // { name: "Harvard University",  },
  // { name: "Sysmex",  },
  // { name: "Yonsei Univ",  },
  // { name: "Queen's University Belfast",  },
];
