export default [
  { name: "California Polytechnic State University", userCount: 214 },
  { name: "Thomas Jefferson University", userCount: 214 },
  { name: "University of California San Francisco", userCount: 60 },
  { name: "University of Cambridge", userCount: 60 },
  { name: "Long Island University", userCount: 60 },
  { name: "University of Edinburgh", userCount: 60 },
  { name: "University of Pittsburgh", userCount: 60 },
  { name: "University of Copenhagen", userCount: 23 },
  { name: "Karolinska Institutet (Sweden)", userCount: 23 },
  { name: "Universidad de los Andes (Colombia)", userCount: 23 },
  { name: "Monash University", userCount: 19 },
  { name: "University of California San Diego", userCount: 19 },
  { name: "University of Toronto", userCount: 19 },
  { name: "Linköpings Universitet (Sweden)", userCount: 18 },
  { name: "University of Michigan", userCount: 18 },
  { name: "National Autonomous University of Mexico", userCount: 17 },
  { name: "University of Oxford", userCount: 17 },
  { name: "Inserm (France)", userCount: 16 },
  { name: "CNRS (France)", userCount: 16 },
  { name: "University of Minnesota", userCount: 13 },
  { name: "University of Manchester", userCount: 13 },
  { name: "University of Ottawa", userCount: 13 },
  { name: "UCLA", userCount: 13 },
  { name: "Yale University", userCount: 13 },
  { name: "University of Pennsylvania", userCount: 13 },
  { name: "Ludwig Maximilian University of Munich", userCount: 12 },
  { name: "UCL (London)", userCount: 12 },
  { name: "Cardiff University", userCount: 12 },
  { name: "Duke University", userCount: 12 },
  { name: "University of Cincinnati", userCount: 12 },
  { name: "Johns Hopkins", userCount: 11 },
  { name: "Newcastle University", userCount: 11 },
  { name: "Stanford University", userCount: 11 },
  { name: "Mayo Clinic", userCount: 11 },
  { name: "University of Florida", userCount: 10 },
  { name: "UC Berkeley", userCount: 10 },
  { name: "University of Sheffield", userCount: 10 },
  { name: "King's College London", userCount: 10 },
  { name: "Imperial College London", userCount: 10 },
  { name: "University College London", userCount: 10 },
  { name: "University of Iowa", userCount: 10 },
  { name: "MIT", userCount: 10 },
  { name: "Emory University", userCount: 10 },
  { name: "Dalhousie University", userCount: 9 },
  { name: "Broad Institute", userCount: 9 },
  { name: "UAB", userCount: 9 },
  { name: "University of Birmingham", userCount: 9 },
  { name: "Columbia University", userCount: 9 },
  { name: "University of Leicester", userCount: 9 },
  { name: "CINVESTAV (Mexico)", userCount: 9 },
  { name: "Trinity College Dublin", userCount: 9 },
  { name: "Seoul National University", userCount: 9 },
  { name: "Tel Aviv university", userCount: 9 },
  { name: "National University of Singapore", userCount: 9 },
  { name: "Northwestern University", userCount: 9 },
  { name: "University of Illinois", userCount: 8 },
  { name: "University of Dundee", userCount: 8 },
  { name: "Jagiellonian University (Poland)", userCount: 8 },
  { name: "Linköping University", userCount: 8 },
  { name: "UCD", userCount: 8 },
  { name: "University of glasgow", userCount: 8 },
  { name: "University of Oregon", userCount: 8 },
  { name: "University of Nottingham", userCount: 8 },
  { name: "Freie Universität Berlin", userCount: 8 },
  { name: "UBC", userCount: 8 },
  { name: "University of Perugia", userCount: 7 },
  { name: "HKU", userCount: 7 },
  { name: "NUS", userCount: 7 },
  { name: "DRFZ", userCount: 7 },
  { name: "MSKCC", userCount: 7 },
  { name: "University of Vienna", userCount: 7 },
  { name: "Baylor College of Medicine", userCount: 7 },
  { name: "Albert Einstein College of Medicine", userCount: 7 },
  { name: "University of British Columbia", userCount: 7 },
  { name: "German Cancer Research Center", userCount: 7 },
  { name: "Boston Children's Hospital", userCount: 7 },
  { name: "Penn State College of Medicine", userCount: 7 },
  { name: "University of Sydney", userCount: 7 },
  { name: "The Hebrew University of Jerusalem", userCount: 7 },
  { name: "The University of Hong Kong", userCount: 7 },
  { name: "Cincinnati Children's Hospital", userCount: 7 },
  { name: "University of Twente", userCount: 7 },
  { name: "Children's Hospital of Philadelphia", userCount: 7 },
  { name: "University of Basel", userCount: 7 },
  { name: "University of Sao Paulo", userCount: 7 },
  { name: "Osaka university", userCount: 7 },
  { name: "Mount Sinai Hospital", userCount: 6 },
  { name: "Dana Farber Cancer Institute", userCount: 6 },
  { name: "Purdue University", userCount: 6 },
  { name: "BSRC Alexander Fleming", userCount: 6 },
  { name: "Research Center Borstel", userCount: 6 },
  {
    name: "Landspítali - The National University Hospital of Iceland",
    userCount: 6,
  },
  { name: "Instituto de Medicina Tropical de São Paulo", userCount: 6 },
  { name: "Université de Montréal", userCount: 6 },
  { name: "University of Groningen", userCount: 6 },
  { name: "University of Lausanne", userCount: 6 },
  { name: "Harvard University", userCount: 6 },
  { name: "Sysmex", userCount: 6 },
  { name: "Yonsei Univ", userCount: 6 },
  { name: "Queen's University Belfast", userCount: 6 },
];
